services:
  - type: web
    name: vk-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python vk_bot.py"
    envVars:
      - key: VK_BOT_TOKEN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false