services:
  - type: web
    name: vk-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn vk_bot:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: VK_BOT_TOKEN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        value: 10000
